name: SlimeTinker
author: Sefiraat
description: An addon that is trying to recreate Tinkers Construct within Slimefun. Adds new customisable tools with leveling and modifiers.
main: io.github.sefiraat.slimetinker.SlimeTinker
website: https://github.com/Sefiraat/SlimeTinker
version: ${project.version}
api-version: 1.20
depend:
  - Slimefun
softdepend:
  - GuizhanLibPlugin
  - InfinityExpansion2
  - SlimefunWarfare
  - DynaTech
  - LiteXpansion
  - TranscEndence
  - Networks
commands:
  slimetinker:
    description: /slimetinker
    usage: /slimetinker <sub>
    aliases: [ st, tinker ]
